### ISSUE TITLE
Add Disclaimer in README that this repo is non-functional

### ISSUE THREAD

**Issue by itsdfish** [TuringLang/MCMCTempering.jl#135]
Hi,

I recommend adding a disclaimer at the top of the README indicating that this repo is non-functional. Providing a timeline for fixing the repo would also be helpful. Otherwise, users might be mislead into believing that the repo is functional and will [encounter errors](https://github.com/TuringLang/MCMCTempering.jl/issues/134), which reflects poorly on the community.

**Comment by yebai** [comment]
Hi @itsdfish - thanks for reaching out. I am aware of this issue. We will try to merge #133 over the summer.

**Comment by itsdfish** [comment]
Hi @yebai. Thanks for your reply. I am willing to submit a PR if you think this would be useful. Thanks!

**Comment by yebai** [comment]
that sounds great! @itsdfish

**Comment by itsdfish** [comment]
Hi,

I noticed  there has been some development on this package. I think the warning can be removed if it is now in working order.
